[package]
name = "error-code-derive"
version = "0.1.0"
edition = "2021"
license = "MIT"
[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.91", features = ["extra-traits"] }
